### ISSUE TITLE
Default behavior of change_parameters

### ISSUE THREAD

**Issue by niklasschmitz** [JuliaMolSim/DftFunctionals.jl#16]
The currect interface provides a default implementation of `change_parameters` as an identity fallback:
```julia
change_parameters(f::Functional, ::AbstractArray; keep_identifier=false) = f
```
This can lead to some unexpected behavior downstream (in particular with AD and type conversion, if someone implements a new XC but forgot to overload change_parameters), so it may be worth to remove this default implementation and leave it only as a declaration of the function name. This would then just raise a loud MethodError, where needed.

**Comment by mfherbst** [comment]
Agree, PR appreciated !
